[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src https://api.bybit.com https://fapi.bybit.com https://api.exchangerate-api.com https://api.coingecko.com; img-src 'self' data: https:; font-src 'self' data:;"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/javascript"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/css"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Content-Type = "text/html; charset=utf-8"

[build.environment]
  NODE_VERSION = "18" 